[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version="0.4.22", features=["release_max_level_warn"] }
simple_logger = "5.0.0"
serde = { version = "1.0.216", features = ["derive"] }
